#We need a decent ubuntu dist
sudo: required
dist: trusty

language: cpp
compiler: 
    - clang
    - gcc
addons:
    apt:
        sources:
            - george-edison55-precise-backports #cmake 3
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.8
        packages:
            - gcc-5
            - g++-5
            - clang-3.8
            - cmake
            - cmake-data
script:
    - mkdir bld
    - cd bld/; cmake -D useSDK=OFF ../
    - make runUT
